<option value="School">School </option>
<option value="10th">10th</option>
<option value="12th">12th</option>
<option value="Mathamatics">Mathamatics</option>
<option value="Science">Science</option>
<option value="Biology">Biology</option>
<option value="Chemistry">Chemistry</option>
<option value="Engineering">Engineering</option>
<option value="Medicals">Medicals</option>
<option value="English">English</option>
<option value="Physics">Physics</option>
<option value="Commerce">Commerce</option>
<option value="Accounting">Accounting</option>
<option value="Business">Business</option>
<option value="Management">Management</option>
<option value="Computer Science">Computer Science</option>
<option value="Action and Adventure">Action and Adventure</option>
<option value="Anthology">Anthology</option>
<option value="Classic">Classic</option>
<option value="Comic and Graphic Novel">Comic and Graphic Novel</option>
<option value="Crime and Detective">Crime and Detective</option>
<option value="Drama">Drama</option>
<option value="Fable">Fable</option>
<option value="Fairy Tale">Fairy Tale</option>
<option value="Fan-Fiction">Fan-Fiction</option>
<option value="Fantasy">Fantasy</option>
<option value="Historical Fiction">Historical Fiction</option>
<option value="Historical ">Historical</option>
<option value="Horror">Horror</option>
<option value="Humor">Humor</option>
<option value="Legend">Legend</option>
<option value="Magical Realism">Magical Realism</option>
<option value="Spiritual">Spiritual</option>
<option value="Mystery">Mystery</option>
<option value="Mythology">Mythology</option>
<option value="Realistic Fiction">Realistic Fiction</option>
<option value="Romance">Romance</option>
<option value="Satire">Satire</option>
<option value="Science Fiction (Sci-Fi)">Science Fiction (Sci-Fi)</option>
<option value="Short Story">Short Story</option>
<option value="Suspense / Thriller">Suspense / Thriller</option>
<option value="Biography / Autobiography">Biography / Autobiography</option>
<option value="Essay">Essay </option>
<option value="Memoir">Memoir </option>
<option value="Narrative Nonfiction">Narrative Nonfiction </option>
<option value="Periodicals">Periodicals </option>
<option value="Reference Books">Reference Books</option> 
<option value="Self - help Book">Self-help Book </option>
<option value="Speech">Speech</option>  
<option value="Textbook">Textbook</option> 
<option value="Poetry">Poetry</option>